apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
  labels:
    app: maven-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app-container
          image: $IMAGE
          ports:
            - containerPort: 5000
