name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Determine Version Increment Strategy
        id: version_strategy
        shell: bash
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          if [[ "$BRANCH" == "master" ]]; then
            INCREMENT="minor"
          elif [[ "$BRANCH" == "dev" ]]; then
            INCREMENT="patch"
          else
            INCREMENT="build"
          fi
          echo "increment=$INCREMENT" >> $GITHUB_OUTPUT

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: latest_tag
        shell: bash
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Increment Version Number
        id: version
        shell: bash
        run: |
          LATEST_TAG="${{ steps.latest_tag.outputs.latest_tag }}"
          INCREMENT="${{ steps.version_strategy.outputs.increment }}"

          # Extract version components
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)

          if [[ "$INCREMENT" == "minor" ]]; then
            MINOR=$((MINOR+1))
            PATCH=0
          elif [[ "$INCREMENT" == "patch" ]]; then
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Tag New Version
        shell: bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"

      - name: Build Docker Image
        run: |
          docker build --build-arg="VERSION=${{ steps.version.outputs.new_version }}" -t "yohaikorem/maven_app:${{ steps.version.outputs.new_version }}" .

      - name: Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          docker tag "yohaikorem/maven_app:${{ steps.version.outputs.new_version }}" yohaikorem/maven_app:latest
          docker push "yohaikorem/maven_app:${{ steps.version.outputs.new_version }}"
