name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --build-arg="VERSION=${{ 1.0.0 }}" -t yohaikorem/maven_app:${{ 1.0.0 }} .

      - name: Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          docker tag yohaikorem/maven_app:${{ 1.0.0 }} yohaikorem/maven_app:latest
          docker push yohaikorem/maven_app:${{ 1.0.0 }}
