name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: Increment version number
        id: version
        shell: bash
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          INCREMENT=""

          if [[ "$BRANCH" == "master" ]]; then
            INCREMENT="Minor"
          elif [[ "$BRANCH" == "dev" ]]; then
            INCREMENT="Patch"
          else
            INCREMENT="Build"
          fi

          echo "increment=$INCREMENT" >> $GITHUB_OUTPUT

      - name: Print Increment Strategy
        shell: bash
        run: echo "${{ steps.version.outputs.increment }}"

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --build-arg="VERSION=1" -t yohaikorem/maven_app:1 .

      - name: Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          docker tag yohaikorem/maven_app:1 yohaikorem/maven_app:latest
          docker push yohaikorem/maven_app:1
