name: Terraform pipeline

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.EC2_SECRET_KEY }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Terraform Init
        working-directory: ./tf
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var container_image=yohaikorem/maven_app
        working-directory: ./tf
