name: Terraform pipeline

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0' # Specify the version here

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply
      - name: Setup instance with Terraform
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_REPO_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.EC2_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
          TF_ACTION_WORKING_DIR: 'tf'

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_REPO_TOKEN }}
          TF_ACTION_WORKING_DIR: 'tf'
          AWS_ACCESS_KEY: ${{ secrets.EC2_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
